# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LWP-Protocol-https-SocksChain10
version:      1.3
version_from: SocksChain10.pm
installdirs:  site
requires:
    IO::Socket::SSL:               
    LWP:                           
    Net::SC:                       1.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
